#' Copy an Internal Function from Another Package
#'
#' This utility copies an internal (unexported) function from another installed package
#' and writes it to your package's `R/` directory. It supports memoised functions by
#' stripping bytecode and environment references for cleaner source extraction.
#'
#' This is useful for packages under a compatible open-source license when upstream
#' authors have not exported a function, but the logic is needed for stable usage.
#'
#' @param pkg A character string naming the package (e.g., `"rmaADM"`).
#' @param fun_name A character string naming the internal function to copy.
#' @param dest_dir A character string for the destination directory (default is `"R"`).
#'
#' @return Writes a `.R` file containing the copied function to the destination directory.
#' @importFrom stats filter time
#' @importFrom utils capture.output getFromNamespace
#' @examples
#' \dontrun{
#' copy_3rd_party_function("rmaADM", "locate_download_link")
#' copy_3rd_party_function("rmaADM", "clean_data")
#' }
#'
#' @export
copy_3rd_party_function <- function(pkg, fun_name, dest_dir = "R") {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop(sprintf("Package '%s' is not installed.", pkg))
  }

  # Extract and unwrap if memoised
  obj <- getFromNamespace(fun_name, pkg)
  if ("memoised_function" %in% class(obj)) {
    message(sprintf("ℹ Detected memoised function '%s:::%s' – unwrapping.", pkg, fun_name))
    obj <- environment(obj)$f
  }

  # Convert to text and clean
  fun_text <- capture.output(obj)
  fun_text <- fun_text[!grepl("bytecode|environment|Memoised Function", fun_text)]
  fun_text <- c(paste0(fun_name, " <- "), fun_text)

  # Parse for pkg::fun usage
  reg <- gregexpr("([A-Za-z0-9\\.]+)::([A-Za-z0-9_\\.]+)", fun_text, perl = TRUE)
  matches <- unlist(regmatches(fun_text, reg))
  pkg_fun_df <- if (length(matches)) {
    unique(do.call(rbind, strsplit(matches, "::", fixed = TRUE)))
  } else {
    matrix(ncol = 2, dimnames = list(NULL, c("pkg", "fun")))
  }

  # Format import statements
  import_lines <- c()
  if (nrow(pkg_fun_df) > 0) {
    pkgs <- unique(pkg_fun_df[, 1])
    for (p in pkgs) {
      funs <- pkg_fun_df[pkg_fun_df[, 1] == p, 2]
      if (length(funs) <= 3) {
        import_lines <- c(import_lines, sprintf("#' @importFrom %s %s", p, paste(funs, collapse = " ")))
      } else {
        import_lines <- c(import_lines, sprintf("#' @import %s", p))
      }
    }
  }

  # Roxygen2-compatible header
  header <- c(
    sprintf("#' @title %s (Copied from %s)", fun_name, pkg),
    sprintf("#' @description Copied from internal function `%s:::%s`", pkg, fun_name),
    "#' @details Generated by `copy_3rd_party_function()` for reuse under a compatible license.",
    "#'",
    "#' @author Unknown",
    "#' @source Internal function from external package",
    "#'"
  )

  # Add import statements
  header <- c(header, import_lines, "#'", sprintf("#' @note Copied on %s", Sys.Date()), "")

  # Ensure destination exists
  if (!dir.exists(dest_dir)) dir.create(dest_dir, recursive = TRUE)

  # Write to file
  file_path <- file.path(dest_dir, paste0(fun_name, ".R"))
  writeLines(c(header, fun_text), con = file_path)

  message(sprintf("✅ Function '%s:::%s' written to '%s'", pkg, fun_name, file_path))
  invisible(file_path)
}


copy_3rd_party_function(pkg="rmaADM", fun_name="clean_data")
copy_3rd_party_function("rmaADM", fun_name="locate_download_link")
