#' @name layouts_fcip
#' @title Column Layouts for Federal Crop Insurance Program (FCIP) Data
#' @description 
#' Use these layouts when reading raw FCIP CSV exports or when constructing  
#' data frames for analysis. Ensures consistent column ordering and naming across  
#' multiple report types.
#' @source USDA-RMA
layouts_fcip <- list(
  sobtpu = c(
      "commodity_year",
      "state_code",
      "state_name",
      "state_abbreviation",
      "county_code",
      "county_name",
      "commodity_code",
      "commodity_name",
      "insurance_plan_code",
      "insurance_plan_abbreviation",
      "coverage_type_code",
      "coverage_level_percent",
      "delivery_id",
      "type_code",
      "type_name",
      "practice_code",
      "practice_name",
      "unit_structure_code",
      "unit_structure_name",
      "net_reporting_level_amount",
      "reporting_level_type",
      "liability_amount",
      "total_premium_amount",
      "subsidy_amount",
      "indemnity_amount",
      "loss_ratio",
      "endorsed_commodity_reporting_level_amount"),
  
  sobcov = c(
      "commodity_year",
      "state_code",
      "state_abbreviation",
      "county_code",
      "county_name",
      "commodity_code",
      "commodity_name",
      "insurance_plan_code",
      "insurance_plan_abbreviation",
      "coverage_type_code",
      "delivery_type",
      "coverage_level_percent",
      "policies_sold_count",
      "policies_earning_premium_count",
      "policies_indemnified_count",
      "units_earning_premium_count",
      "units_indemnified_count",
      "quantity_type",
      "net_reported_quantity",
      "endorsed_companion_acres",
      "liability_amount",
      "total_premium_amount",
      "subsidy_amount",
      "state_private_subsidy",
      "additional_subsidy",
      "efa_premium_discount",
      "indemnity_amount",
      "loss_ratio"),
  
  lgm = c(
      "reinsurance_year",
      "commodity_year",
      "state_code",
      "state_abbreviation",
      "county_code",
      "county_name",
      "commodity_code",
      "commodity_name",
      "insurance_plan_code",
      "insurance_plan_name",
      "type_code",
      "type_name",
      "practice_code",
      "practice_name",
      "sales_effective_date",
      paste0("target_marketings_", 1:11),
      paste0("corn_equivalent_", 2:11),
      paste0("soybean_meal_equivalent_", 2:11),
      "endorsements_earning_premium",
      "endorsements_indemnified",
      "deductible",
      "live_cattle_target_weight_quantity",
      "feeder_cattle_target_weight_quantity",
      "corn_target_weight_quantity",
      "liability_amount",
      "total_premium_amount",
      "subsidy_amount",
      "producer_paid_premium_amount",
      "indemnity_amount"),
  
  lrp = c(
      "reinsurance_year",
      "commodity_year",
      "state_code",
      "state_abbreviation",
      "county_code",
      "county_name",
      "commodity_code",
      "commodity_name",
      "insurance_plan_code",
      "insurance_plan_name",
      "type_code",
      "type_name",
      "practice_code",
      "practice_name",
      "sales_effective_date",
      "endorsement_length",
      "coverage_price",
      "expected_end_value",
      "coverage_level_percent",
      "rate",
      "cost_per_cwt",
      "end_date",
      "endorsements_earning_premium",
      "endorsements_indemnified",
      "net_number_of_head",
      "total_weight",
      "subsidy_amount",
      "total_premium_amount",
      "producer_paid_premium_amount",
      "liability_amount",
      "indemnity_amount"),
  
  # Cause of Loss Summary of Business [1989-current]
  colsom = c(
    "commodity_year",
    "state_code",
    "state_abbreviation",
    "county_code",
    "county_name",
    "commodity_code",
    "commodity_name",
    "insurance_plan_code",
    "insurance_plan_abbreviation",
    "coverage_type_code",
    "stage_code",
    "cause_of_loss_code",
    "cause_of_loss_description",
    "month_of_loss",
    "month_of_loss_name",
    "year_of_loss",
    "policies_earning_premium_count",
    "policies_indemnified_count",
    "net_planted_quantity",
    "net_endorsed_acres",
    "liability_amount",
    "total_premium_amount",
    "producer_paid_premium_amount",
    "subsidy_amount",
    "state_private_subsidy",
    "additional_subsidy",
    "efa_premium_discount",
    "net_determined_quantity",
    "indemnity_amount",
    "loss_ratio"),
  
  # Cause of Loss Indemnities Only 
  col_indem = c(
    "commodity_year",
    "state_code",
    "state_abbreviation",
    "county_code",
    "county_name",
    "commodity_code",
    "commodity_name",
    "insurance_plan_code",
    "insurance_plan_abbreviation",
    "cause_of_loss_code",
    "cause_of_loss_description",
    "indemnity_amount"),
  
  # Cause of Loss Indemnities With Month of Loss
  col_month = c(
    "commodity_year",
    "state_code",
    "state_abbreviation",
    "county_code",
    "county_name",
    "commodity_code",
    "commodity_name",
    "insurance_plan_code",
    "insurance_plan_abbreviation",
    "cause_of_loss_code",
    "cause_of_loss_description",
    "month_of_loss",
    "month_of_loss_abbreviation",
    "indemnity_amount"),
  
  # Cause of Loss Summary of Business [1989-2009]
  col_sob = c(
    "commodity_year",
    "state_code",
    "state_abbreviation",
    "county_code",
    "county_name",
    "commodity_code",
    "commodity_name",
    "insurance_plan_code",
    "insurance_plan_abbreviation",
    "coverage_type_code",
    "cause_of_loss_code",
    "cause_of_loss_description",
    "policies_earning_premium_count",
    "policies_indemnified_count",
    "net_planted_quantity",
    "liability_amount",
    "total_premium_amount",
    "subsidy_amount",
    "indemnity_amount",
    "loss_ratio")
  )


